# Generated by Django 2.0.1 on 2020-04-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=100)),
                ('LastName', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=500)),
                ('EmailId', models.CharField(default='', max_length=120)),
                ('PhoneNo', models.CharField(default='', max_length=12)),
                ('Password', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
